### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Sauro98** [Sauro98/CVProject#1]
# Cv Project roadmap 

- [x] 1. B&W + HE (class + program) (Anna)
- [x] 2. BB (program) (Samuele)
- [x] 3. Segmentation (class + program) (Ivano,Samuele)

- [x] 4. Create dataset
    - [x] Boats
    - [x] Sea 

- [x] 5. Class to extract sift features based on masks (Anna)
   - [x] 5.a program to pre-extract features with labels for each image (Samuele)

- [x] 6/7 ML on sea and boats (Tutti)
- [x] 8. Boats tracking (Anna)
- [x] Relazione
